# Generated by Django 4.2.16 on 2025-06-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1app', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
