# Generated by Django 4.2.16 on 2025-06-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web1app', '0004_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web1app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1app.product')),
            ],
        ),
    ]
