# Generated by Django 4.2.16 on 2025-06-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1app', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
